service:
  sweater:
    relations_types:
    - name: answers
    - name: negates
    - name: may be
    - name: means
    - name: therefore
    - name: includes
    chest:
      env:
        opts:
          sophia:
            path: /tmp/wool/sweater/data
          db:
            d: &ddbs
              compression: zstd
      index:
        env:
          opts:
            sophia:
              path: /tmp/wool/sweater/index
            db:
              t2o:
                *ddbs
              o2t:
                *ddbs
              d2v:
                *ddbs
              c:
                *ddbs
  users:
    chest:
      env:
        opts:
          sophia:
            path: /tmp/wool/users/data
          db:
            d: &ddbs
              compression: zstd
      index:
        env:
          opts:
            sophia:
              path: /tmp/wool/users/index
            db:
              t2o:
                *ddbs
              o2t:
                *ddbs
              d2v:
                *ddbs
              c:
                *ddbs
